### ISSUE TITLE
Complete CodeWars Katas

### ISSUE THREAD

**Issue by GoodGuyGregory** [GoodGuyGregory/codewars_katas#1]
Please Commit Kata Solutions to this Repo for Hacktobefest 2020

**Comment by GoodGuyGregory** [comment]
Hacktober Fest 2020 has been complete

**Comment by GoodGuyGregory** [comment]
@yafiwebdev @nobalpha  Thanks for the PRs I hope you're doing well in these crazy times! 🤘

**Comment by yafiwebdev** [comment]
@GoodGuyGregory 
Hey, thanks, man! 
Hacktoberfest took a lot of my time as I was managing a, then, very active repo, so now I'm getting back to my own projects to catch up, and I've been going through a lot of interviews, sorry that I haven't contributed more to your repo yet!

Hope you are doing well also
All the best!

**Comment by nobalpha** [comment]
@GoodGuyGregory thank you so much for this chance, I appreciate it! And as soon as I solve more problems, I'll post them here! I guess we can add solution's descriptions as well for mates who can't understand the logic from the code, maybe?

**Comment by GoodGuyGregory** [comment]
@nobalpha  oh yeah I have been adding notes etc for each of the katas I knock out in order to help me later solve them. helps me with learning and refreshing on the languages
